anni-config:
  ==: "AnnihilationConfig"
  swmLoaderName: "file"
  storageSourceTypeName: "file"
  userStorageCredential:
    userName: ""
    password: ""
    ip: 127.0.0.1
    port: "3306"
    database: "annihilation-data"